import { sidebar } from "vuepress-theme-hope";

export const zhSidebar = sidebar({
    "/Overview/": [
      "",
      "TechnicalArchitecture",
      "Changelog",
    ],
    "/QuickStart/": [
      // "",
      "Environment",
      "Register",
      "BasicCommands",
      "Contribute",
      "HowToAsk",
    ],
    "/SurvivalGuide/": [
        {
            text: "生存服介绍",
            icon: "material-icon-theme:minecraft",
            link: "/SurvivalGuide/SurvivalServer/",
            exact: true,
            prefix: "/SurvivalGuide/SurvivalServer/",
            collapsible: false,
            expanded: true,
            children: [
                "Survival-Main",
                "Survival-Industry",
                "Survival-Resource"
            ],
        },
        {
            text: "经济系统",
            icon: "noto:bank",
            link: "/SurvivalGuide/EconomicSystem/",
            exact: true,
            prefix: "/SurvivalGuide/EconomicSystem/",
            collapsible: false,
            expanded: true,
            children: [
                "MakeMoney",
                "Residence",
                "Shop"
            ],
        },
        {
            text: "机器手册",
            icon: "fxemoji:bluebook",
            link: "/SurvivalGuide/MachineInstruction/",
            exact: true,
        },
        {
            text: "常见问题",
            icon: "fluent-color:notebook-question-mark-20",
            link: "/SurvivalGuide/Support/",
            exact: true,
            prefix: "/SurvivalGuide/Support/",
            collapsible: false,
            expanded: true,
            children: [
                "Service",
                "Technical",
            ],
        },
    ],

    "/PluginIntroduction/": [
      "",
      {
        text: "自研插件",
        icon: "mdi:hammer-wrench",
        prefix: "/PluginIntroduction/",
        collapsible: false,
        expanded: true,
        children: [
          "DeathChest",
          "GlobalChat",
          "RandomTeleport",
          "ServerTeleport",
        ],
      },
      {
        text: "开源插件",
        icon: "mdi:open-source-initiative",
        prefix: "/PluginIntroduction/",
        collapsible: false,
        expanded: true,
        children: [
          "AdvancedPortals",
          "AngelChest",
          "Bluemap",
          "CoreProtect",
          "DecentHolograms",
          "Dynmap",
          "FastAsyncWorldEdit",
          "GSit",
          "HuskSync",
          "LeavesFakePlayer",
          "LuckPerms",
          "MultiverseCore",
          "PlotSquared",
          "Residence",
          "SimpleVoiceChat",
        ],
      },
    ],
    "/ServerIntroduction/": "structure",
    "/Chronicle/": [
      "",
      {
        text: "正传",
        icon: "fxemoji:bookmarktab",
        link: "/Chronicle/TimeLine",
        prefix: "/Chronicle/",
        collapsible: false,
        expanded: true,
        children: [
          "Generation3",
          "Generation4",
          "Generation5",
        ],
      },
      {
        text: "玩家档案",
        icon: "fluent-emoji:busts-in-silhouette",
        link: "/Chronicle/PlayerProfiles/",
        exact: true,
        prefix: "/Chronicle/PlayerProfiles/",
        collapsible: false,
        expanded: true,
        children: [
          {
            text: "A~D",
            icon: "mdi:alpha-a-circle",
            collapsible: true,
            children: [
              "ACertainPlayer",
              "ADCa",
              "Altair",
              "Aplence",
              "ARKsealin",
              "Baishui2333",
              "mc_bookman",
              "CCapsule",
              "Dai_mao",
              "Daytona_q",
            ],
          },
          {
            text: "E~G",
            icon: "mdi:alpha-e-circle",
            collapsible: true,
            children: ["Evalyn", "FRIEDparrot"],
          },
          {
            text: "H~K",
            icon: "mdi:alpha-h-circle",
            collapsible: true,
            children: [
              "Hakumei",
              "Hoshizorarin",
              "Irving_Dragon",
              "JingKaiNing",
              "July",
              "KCN",
              "Kuake",
            ],
          },
          {
            text: "L~N",
            icon: "mdi:alpha-l-circle",
            collapsible: true,
            children: [
              "LLLLL",
              "lyyyyds",
              "maple",
              "mark_kram",
              "MikuMikuMi",
              "Milk_Am",
              "Minecraft",
              "MMRlove",
              "Monikard",
            ],
          },
          {
            text: "O~Q",
            icon: "mdi:alpha-o-circle",
            collapsible: true,
            children: [
              "OldChuaN_",
              "Kurumisama",
              "Orange_Chengjun",
              "panbaiyuan",
              "PrettyReol",
              "poiuy",
            ],
          },
          {
            text: "R~T",
            icon: "mdi:alpha-r-circle",
            collapsible: true,
            children: [
              "Rinryrethoic",
              "rit",
              "sakura",
              "sanae",
              "shenjack",
              "Sirius0v0",
              "SUPER2FH",
              "TeachingFeelings",
              "threecircles",
            ],
          },
          {
            text: "U~W",
            icon: "mdi:alpha-u-circle",
            collapsible: true,
            children: ["Umitsuki", "westddd720", "wreg"],
          },
          {
            text: "X~Z",
            icon: "mdi:alpha-x-circle",
            collapsible: true,
            children: [
              "xiaoxiaolu",
              "Xuanzha",
              "YiMeng",
              "yuguidahai",
              "ZhishuiDuqiu",
            ],
          },
        ],
      },
      {
        text: "关键事件",
        icon: "twemoji:warning",
        link: "/Chronicle/KeyEvents/",
        prefix: "/Chronicle/KeyEvents/",
        collapsible: false,
        expanded: true,
        children: ["MiningIntrusion"],
      },
    ],

});
