const playerProfileSlugs = [
  "ACertainPlayer",
  "ADCa",
  "Altair",
  "Aplence",
  "ARKsealin",
  "Baishui2333",
  "mc_bookman",
  "CCapsule",
  "Dai_mao",
  "Daytona_q",
  "Evalyn",
  "FRIEDparrot",
  "Hakumei",
  "Hoshizorarin",
  "Irving_Dragon",
  "JingKaiNing",
  "July",
  "KCN",
  "Kuake",
  "LLLLL",
  "lyyyyds",
  "maple",
  "mark_kram",
  "MikuMikuMi",
  "Milk_Am",
  "Minecraft",
  "MMRlove",
  "Monikard",
  "OldChuaN_",
  "Kurumisama",
  "Orange_Chengjun",
  "panbaiyuan",
  "PrettyReol",
  "poiuy",
  "Rinryrethoic",
  "rit",
  "sakura",
  "sanae",
  "shenjack",
  "Sirius0v0",
  "SUPER2FH",
  "TeachingFeelings",
  "threecircles",
  "Umitsuki",
  "westddd720",
  "wreg",
  "xiaoxiaolu",
  "Xuanzha",
  "YiMeng",
  "yuguidahai",
  "ZhishuiDuqiu",
];

export const pathRedirects: Record<string, string> = {
  "/MachineInstruction/": "/SurvivalGuide/MachineInstruction/",
  "/MachineInstruction.html": "/SurvivalGuide/MachineInstruction/",
  "/PlayerProfiles/": "/Chronicle/PlayerProfiles/",
  "/PlayerProfiles.html": "/Chronicle/PlayerProfiles/",
  ...Object.fromEntries(
    playerProfileSlugs.map((slug) => [
      `/PlayerProfiles/${slug}.html`,
      `/Chronicle/PlayerProfiles/${slug}.html`,
    ]),
  ),
};
